export enum Category{
    HOME='home',
    THOI_SU = 'thoi-su',
    THE_GIOI='the-gioi',
    KINH_TE = 'kinh-te',
    XA_HOI='xa-hoi',
    PHAP_LUAT='phap-luat',
    VAN_HOA='van-hoa',
    GIAO_DUC='giao-duc',
    THE_THAO='the-thao',
    HO_SO='ho-so',
    QUAN_SU='quan-su',
    KHOA_HOC_CONG_NGHE='khoa-hoc-cong-nghe',
    BIEN_DAO='bien-dao',
    Y_TE='y-te',
    DIA_PHUONG='dia-phuong',
    VIDEO='video',
    GOC_NHIN='goc-nhin',
    ANH='anh',
    INFORGRAPHICS='inforgraphics',
    DAC_BIET='dac-biet',
    BAN_DOC='ban-doc',
    DAN_TOC_MIEN_NUI='dan-toc-mien-nui',
    ANH_360='anh-360'
}
export const categoryName ={
    [Category.HOME]: 'Trang chủ',
    [Category.THOI_SU]: 'Thời sự',
    [Category.THE_GIOI]: 'Thế Giới',
    [Category.KINH_TE]: ' Kinh tế',
    [Category.XA_HOI]: ' Xã hội',
    [Category.PHAP_LUAT]: 'Pháp luật',
    [Category.VAN_HOA]: 'Văn hóa',
    [Category.GIAO_DUC]: 'Giáo dục',
    [Category.THE_THAO]: 'Thể thao',
    [Category.HO_SO]: 'Hồ sơ',
    [Category.QUAN_SU]: 'Quân sự',
    [Category.KHOA_HOC_CONG_NGHE]: 'Khoa học công nghệ',
    [Category.BIEN_DAO]: 'Biển đảo',
    [Category.Y_TE]: 'Y tế',
    [Category.DIA_PHUONG]: 'Địa phương',
    [Category.VIDEO]: 'Video',
    [Category.GOC_NHIN]: 'Góc nhìn',
    [Category.ANH]: 'Ảnh',
    [Category.INFORGRAPHICS]: 'Inforgraphics',
    [Category.DAC_BIET]: 'Đặc biệt',
    [Category.BAN_DOC]: 'Bạn đọc',
    [Category.DAN_TOC_MIEN_NUI]: 'Dân tộc miền núi',
    [Category.ANH_360]: 'Ảnh 360'
}